export const features = {
  "Architectural Elements": [
    "Built-Ins",
    "Columns",
    "Crown Mouldings",
    "Curved Stairs",
    "Decorative Mouldings",
    "Double Staircase",
    "Exposed Brick",
    "High Ceilings",
    "Private Entrance",
    "Sound System",
    "Spiral Staircase",
    "Wet Bar",
  ],
  Basements: ["Basement", "Crawl Space", "Full Basement", "Partial Basement"],
  Bathrooms: [
    "Attached Primary Half Bathroom",
    "Bidet",
    "Ceramic Bathroom",
    "Double Entry Bathroom",
    "Double Sink Bathroom",
    "Granite Bathroom",
    "Jacuzzi Tub",
    "Marble Bathroom",
    "Primary Ensuite with Separate Tub",
    "Quarter Bath",
    "Separate Vanities",
    "Soaking Tub",
    "Steam Shower",
    "Two-Person Tub",
    "WaterSense Fixtures",
    "Windowed Bathroom",
  ],
  Closets: [
    "California Closet",
    "Custom Closet",
    "Dual Closet",
    "Walk-in Closet",
  ],
  Exposures: [
    "Eastern Exposure",
    "Northeastern Exposure",
    "Northern Exposure",
    "Northwestern Exposure",
    "Southeastern Exposure",
    "Southern Exposure",
    "Southwestern Exposure",
    "Western Exposure",
  ],
  Fireplaces: [],
  Floors: [
    "Carpet Flooring",
    "Cement Flooring",
    "Ceramic Flooring",
    "Granite Flooring",
    "Hardwood Flooring",
    "Laminate Flooring",
    "Linoleum Flooring",
    "Marble Flooring",
    "Parquet Flooring",
    "Slate Flooring",
    "Tile Flooring",
    "Vinyl Flooring",
    "Wood Flooring",
  ],
  Rooms: [
    "All Bedrooms Upstairs",
    "Bonus Room",
    "Breakfast Area",
    "Breakfast Nook",
    "Center Hall",
    "Den",
    "Dressing Area",
    "Entry",
    "Family Room",
    "Formal Entry",
    "Foyer",
    "Great Room",
    "Guest/Maid's Quarters",
    "Gym/Exercise Room",
    "Home Theatre",
    "In-Law Suite",
    "Library",
    "Living Room",
    "Main Floor Bedroom",
    "Main Floor Master Bedroom",
    "Master Bedroom",
    "Master Suite",
    "Media Room",
    "Office",
    "Powder Room",
    "Sleeping Loft",
  ],
  Building: [
    "Co-purchase & Gift Allowed",
    "Guarantors Allowed",
    "Parents Buying Allowed & Pied-A-Terre Allowed",
  ],
  "Outdoor Space": ["Deck", "Garden", "Patio", "Roof Deck & Terrace @"],
  Location: [
    "Boardwalk",
    "Corner Unit",
    "Penthouse",
    "Waterfront",
    "Water View",
  ],
  Views: [
    "City Views",
    "Garden Views",
    "Park Views",
    "River Views",
    "Skyline View",
    "Water Views",
    "Mountain Views",
  ],
  "Building Amenities": [
    "Basketball Court",
    "Billiards Room",
    "Bocce Ball Court",
    "Club House",
    "Common Media / Recreation Room",
    "Communal Tennis Court",
    "Game Room",
    "Gazebo",
    "Golf Room",
    "Gym",
    "Health Club",
    "Nursery Room",
    "On Site Restaurant",
    "Pet Spa",
    "Screening Room",
    "Shuffle Board",
    "Tennis Court Yoga Studio",
  ],
  "Building Laundry": [
    "Common Laundry",
    "Laundry Area",
    "Laundry in Building",
    "Laundry in Every Unit",
    "Laundry on Every Floor",
    "Laundry on Every Other Floor Laundry Room",
  ],
  "Service Level": [
    "Concierge",
    "Doorman",
    "Full-Time Concierge",
    "Full-Time Doorman",
    "Part-Time Concierge",
    "Part-Time Doorman",
    "Remote Doorman",
  ],
  "Unit Style": [
    "Ground Floor",
    "Junior 4",
    "Junior 1",
    "Loft Style",
    "Maisonette",
    "Over-Storefront",
    "Penthouse",
    "Top Floor",
  ],
};
